-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 15:59:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema deli
-- -----------------------------------------------------
-- Customer: deli
-- 

-- -----------------------------------------------------
-- Schema deli
--
-- Customer: deli
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deli` DEFAULT CHARACTER SET utf8 ;
USE `deli` ;

-- -----------------------------------------------------
-- Table `deli`.`deli_user_sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_sign` (
  `iddeli_user` INT(5) NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddeli_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_contact` (
  `id_user_contact` INT NOT NULL AUTO_INCREMENT,
  `iddeli_user` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `address_user` VARCHAR(45) NULL,
  `phone_user` VARCHAR(45) NOT NULL,
  `admision_date` DATE NOT NULL,
  `birthday` DATE NOT NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(45) NOT NULL,
  `description_category` VARCHAR(45) NOT NULL,
  `others` VARCHAR(45) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_categories` (
  `id_user_category` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `id_category` INT(10) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_categories_id_category` INT NOT NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_user_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_restaurant` (
  `id_restaurant` INT NOT NULL AUTO_INCREMENT,
  `name_restaurant` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `zona` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `tipo_comida` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(20) NOT NULL,
  `incluye` VARCHAR(100) NOT NULL,
  `introduccion` LONGTEXT NOT NULL,
  `p1` LONGTEXT NOT NULL,
  `p2` LONGTEXT NOT NULL,
  `p3` LONGTEXT NOT NULL,
  `logo` VARCHAR(200) NOT NULL,
  `imagen_principal` VARCHAR(200) NOT NULL,
  `link_video` VARCHAR(200) NOT NULL,
  `imagen_2` VARCHAR(200) NOT NULL,
  `imagen_3` VARCHAR(200) NOT NULL,
  `frase` VARCHAR(200) NOT NULL,
  `editorial` VARCHAR(200) NOT NULL,
  `logo_editorial` VARCHAR(200) NOT NULL,
  `sugeridos` VARCHAR(200) NOT NULL,
  `cordenadas` VARCHAR(200) NOT NULL,
  `no_ordenes_deli` INT(5) NOT NULL,
  `no_ordenes_adicionales` INT(5) NOT NULL,
  `deli_categories_id_category` INT NOT NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `prize` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_packages` (
  `id_package` INT NOT NULL AUTO_INCREMENT,
  `name_package` VARCHAR(45) NOT NULL,
  `id_product` INT NOT NULL,
  `deli_product_id_product` INT NOT NULL,
  PRIMARY KEY (`id_package`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_experience` (
  `id_experience` INT NOT NULL AUTO_INCREMENT,
  `name_experience` VARCHAR(45) NOT NULL,
  `id_restaurant` INT NOT NULL,
  `comments` VARCHAR(45) NULL,
  `id_package` INT NOT NULL,
  `deli_restaurant_id_restaurant` INT NOT NULL,
  `deli_packages_id_package` INT NOT NULL,
  PRIMARY KEY (`id_experience`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_surveys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_surveys` (
  `id_survey` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `attention` INT(2) NOT NULL,
  `quality` INT(2) NOT NULL,
  `service` INT(2) NOT NULL,
  `amenity` INT(2) NOT NULL,
  `id_restaurant` INT(10) NOT NULL,
  `date_registered` DATE NOT NULL,
  `comments` VARCHAR(100) NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_survey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_packages_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_packages_routes` (
  `id_package_route` INT NOT NULL,
  `name_package` VARCHAR(45) NOT NULL,
  `id_restaurant` INT NOT NULL,
  `id_product` INT NOT NULL,
  `id_packages` INT NOT NULL AUTO_INCREMENT,
  `deli_product_id_product` INT NOT NULL,
  PRIMARY KEY (`id_packages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_routes` (
  `id_route` INT NOT NULL AUTO_INCREMENT,
  `name_route` VARCHAR(45) NOT NULL,
  `id_package` INT NOT NULL,
  `deli_routes_id_route` INT NOT NULL,
  `deli_packages_routes_id_packages` INT NOT NULL,
  PRIMARY KEY (`id_route`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_global_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_global_schedules` (
  `id_schedule` INT NOT NULL AUTO_INCREMENT,
  `name_schedule` VARCHAR(45) NOT NULL,
  `schedule` INT(10) NOT NULL,
  PRIMARY KEY (`id_schedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_restaurant_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_restaurant_schedule` (
  `id_rschedule` INT NOT NULL AUTO_INCREMENT,
  `id_restaurant` INT(10) NOT NULL,
  `id_schedule` INT(10) NOT NULL,
  `deli_global_schedules_id_schedule` INT NOT NULL,
  `deli_restaurant_id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_rschedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_achievement` (
  `id_uachivement` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `id_achievement` INT(10) NOT NULL,
  `finished` INT(2) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_uachivement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_global_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_global_achievements` (
  `id_achievement` INT NOT NULL AUTO_INCREMENT,
  `name_achievement` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_user_achievement_id_uachivement` INT NOT NULL,
  PRIMARY KEY (`id_achievement`, `deli_user_achievement_id_uachivement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_global_gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_global_gift` (
  `id_gift` INT NOT NULL AUTO_INCREMENT,
  `name_gift` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gift`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_gifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_gifts` (
  `id_ugifts` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `id_gift` INT(10) NOT NULL,
  `date_gift` DATE NOT NULL,
  `deli_global_gift_id_gift` INT NOT NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_ugifts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_codes` (
  `id_ucode` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_code` INT NOT NULL,
  `id_restaurant` INT NOT NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_ucode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_codes` (
  `id_code` INT NOT NULL AUTO_INCREMENT,
  `name_code` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_user_codes_id_ucode` INT NOT NULL,
  PRIMARY KEY (`id_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_trivia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_trivia` (
  `id_utrivia` INT NOT NULL AUTO_INCREMENT,
  `id_trivia` INT NOT NULL,
  `id_user` INT NOT NULL,
  `winner` INT NOT NULL DEFAULT 0,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_utrivia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_trivia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_trivia` (
  `id_trivia` INT NOT NULL AUTO_INCREMENT,
  `name_trivia` VARCHAR(45) NOT NULL,
  `date_trivia` DATE NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_user_trivia_id_utrivia` INT NOT NULL,
  PRIMARY KEY (`id_trivia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_routes` (
  `id_uroutes` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `id_route` INT NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_routes_id_route` INT NOT NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  PRIMARY KEY (`id_uroutes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deli`.`deli_user_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deli`.`deli_user_experience` (
  `id_uexperience` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT(10) NOT NULL,
  `id_experiende` INT(10) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `deli_user_sign_iddeli_user` INT(5) NOT NULL,
  `deli_experience_id_experience` INT NOT NULL,
  PRIMARY KEY (`id_uexperience`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
